import {
    Baby,
    HeartPulse,
    FlaskConical,
    Activity,
    Stethoscope
} from "lucide-react";

// Banco de dados de exames comuns - COM CÓDIGOS TUSS
export const EXAM_DATABASE = {
    laboratorial: [
        // Hematologia
        { name: "Hemograma completo", category: "Hematologia", tuss: "40304361" },
        { name: "Reticulócitos", category: "Hematologia", tuss: "40304370" },
        { name: "Contagem de plaquetas", category: "Hematologia", tuss: "40304159" },
        { name: "Tipagem sanguínea ABO-Rh", category: "Hematologia", tuss: "40306070" },
        { name: "Coombs direto", category: "Hematologia", tuss: "40306062" },
        { name: "Coombs indireto", category: "Hematologia", tuss: "40306054" },
        // Bioquímica - Glicemia
        { name: "Glicemia de jejum", category: "Glicemia", tuss: "40302040" },
        { name: "Glicemia pós-prandial", category: "Glicemia", tuss: "40302059" },
        { name: "Hemoglobina glicada (HbA1c)", category: "Glicemia", tuss: "40302067" },
        { name: "Curva glicêmica (TTOG 75g)", category: "Glicemia", tuss: "40302075" },
        { name: "Frutosamina", category: "Glicemia", tuss: "40301770" },
        // Lipidograma
        { name: "Colesterol total", category: "Lipidograma", tuss: "40301605" },
        { name: "HDL-colesterol", category: "Lipidograma", tuss: "40301583" },
        { name: "LDL-colesterol", category: "Lipidograma", tuss: "40301591" },
        { name: "VLDL-colesterol", category: "Lipidograma", tuss: "40302695" },
        { name: "Triglicerídeos", category: "Lipidograma", tuss: "40302571" },
        { name: "Apolipoproteína A1", category: "Lipidograma", tuss: "40301290" },
        { name: "Apolipoproteína B", category: "Lipidograma", tuss: "40301303" },
        { name: "Lipoproteína (a)", category: "Lipidograma", tuss: "40302318" },
        // Função Renal
        { name: "Ureia", category: "Função Renal", tuss: "40302580" },
        { name: "Creatinina", category: "Função Renal", tuss: "40301630" },
        { name: "Ácido úrico", category: "Função Renal", tuss: "40301036" },
        { name: "Clearance de creatinina", category: "Função Renal", tuss: "40301648" },
        { name: "Cistatina C", category: "Função Renal", tuss: "40301567" },
        { name: "Microalbuminúria", category: "Função Renal", tuss: "40302369" },
        { name: "Relação albumina/creatinina urinária", category: "Função Renal", tuss: "40302377" },
        // Função Hepática
        { name: "TGO (AST)", category: "Função Hepática", tuss: "40302555" },
        { name: "TGP (ALT)", category: "Função Hepática", tuss: "40302563" },
        { name: "Gama GT", category: "Função Hepática", tuss: "40301800" },
        { name: "Fosfatase alcalina", category: "Função Hepática", tuss: "40301753" },
        { name: "Bilirrubinas totais e frações", category: "Função Hepática", tuss: "40301346" },
        { name: "Albumina", category: "Função Hepática", tuss: "40301079" },
        { name: "Proteínas totais e frações", category: "Função Hepática", tuss: "40302423" },
        { name: "LDH (Desidrogenase láctica)", category: "Função Hepática", tuss: "40302300" },
        { name: "Amilase", category: "Função Hepática", tuss: "40301184" },
        { name: "Lipase", category: "Função Hepática", tuss: "40302326" },
        // Tireoide
        { name: "TSH", category: "Tireoide", tuss: "40316130" },
        { name: "T4 livre", category: "Tireoide", tuss: "40316149" },
        { name: "T4 total", category: "Tireoide", tuss: "40316157" },
        { name: "T3 livre", category: "Tireoide", tuss: "40316092" },
        { name: "T3 total", category: "Tireoide", tuss: "40316106" },
        { name: "Anti-TPO", category: "Tireoide", tuss: "40316041" },
        { name: "Anti-tireoglobulina", category: "Tireoide", tuss: "40316033" },
        { name: "Tireoglobulina", category: "Tireoide", tuss: "40316114" },
        // Vitaminas e Minerais
        { name: "Vitamina D (25-OH)", category: "Vitaminas", tuss: "40302610" },
        { name: "Vitamina B12", category: "Vitaminas", tuss: "40302601" },
        { name: "Ácido fólico", category: "Vitaminas", tuss: "40301044" },
        { name: "Vitamina B1 (Tiamina)", category: "Vitaminas", tuss: "40302628" },
        { name: "Vitamina B6", category: "Vitaminas", tuss: "40302636" },
        { name: "Zinco", category: "Vitaminas", tuss: "40302687" },
        { name: "Selênio", category: "Vitaminas", tuss: "40302504" },
        // Metabolismo do Ferro
        { name: "Ferritina", category: "Ferro", tuss: "40301745" },
        { name: "Ferro sérico", category: "Ferro", tuss: "40301737" },
        { name: "Capacidade total de ligação do ferro (TIBC)", category: "Ferro", tuss: "40301508" },
        { name: "Índice de saturação de transferrina", category: "Ferro", tuss: "40302547" },
        { name: "Transferrina", category: "Ferro", tuss: "40302539" },
        // Eletrólitos
        { name: "Sódio", category: "Eletrólitos", tuss: "40302512" },
        { name: "Potássio", category: "Eletrólitos", tuss: "40302415" },
        { name: "Cálcio total", category: "Eletrólitos", tuss: "40301494" },
        { name: "Cálcio iônico", category: "Eletrólitos", tuss: "40301486" },
        { name: "Magnésio", category: "Eletrólitos", tuss: "40302351" },
        { name: "Fósforo", category: "Eletrólitos", tuss: "40302024" },
        { name: "Cloro", category: "Eletrólitos", tuss: "40301575" },
        // Coagulação
        { name: "Tempo de protrombina (TP)", category: "Coagulação", tuss: "40304272" },
        { name: "INR", category: "Coagulação", tuss: "40304280" },
        { name: "TTPa", category: "Coagulação", tuss: "40304299" },
        { name: "Fibrinogênio", category: "Coagulação", tuss: "40304175" },
        { name: "D-dímero", category: "Coagulação", tuss: "40304183" },
        { name: "Tempo de sangramento", category: "Coagulação", tuss: "40304264" },
        // Hormônios
        { name: "Beta-HCG quantitativo", category: "Hormônios", tuss: "40316211" },
        { name: "Prolactina", category: "Hormônios", tuss: "40316289" },
        { name: "Cortisol", category: "Hormônios", tuss: "40316378" },
        { name: "Insulina basal", category: "Hormônios", tuss: "40316386" },
        { name: "HOMA-IR", category: "Hormônios", tuss: "40316394" },
        { name: "FSH", category: "Hormônios", tuss: "40316408" },
        { name: "LH", category: "Hormônios", tuss: "40316416" },
        { name: "Estradiol", category: "Hormônios", tuss: "40316424" },
        { name: "Progesterona", category: "Hormônios", tuss: "40316432" },
        { name: "Testosterona total", category: "Hormônios", tuss: "40316440" },
        { name: "Testosterona livre", category: "Hormônios", tuss: "40316459" },
        { name: "DHEA-S", category: "Hormônios", tuss: "40316467" },
        { name: "PTH (Paratormônio)", category: "Hormônios", tuss: "40316475" },
        { name: "GH (Hormônio do crescimento)", category: "Hormônios", tuss: "40316483" },
        { name: "IGF-1", category: "Hormônios", tuss: "40316491" },
        // Marcadores Tumorais
        { name: "PSA total", category: "Marcadores Tumorais", tuss: "40316505" },
        { name: "PSA livre", category: "Marcadores Tumorais", tuss: "40316513" },
        { name: "CEA", category: "Marcadores Tumorais", tuss: "40316521" },
        { name: "CA 125", category: "Marcadores Tumorais", tuss: "40316548" },
        { name: "CA 19-9", category: "Marcadores Tumorais", tuss: "40316556" },
        { name: "CA 15-3", category: "Marcadores Tumorais", tuss: "40316564" },
        { name: "AFP (Alfafetoproteína)", category: "Marcadores Tumorais", tuss: "40316572" },
        // Urinálise
        { name: "EAS (Urina tipo I)", category: "Urinálise", tuss: "40311163" },
        { name: "Urina 24h (proteínas)", category: "Urinálise", tuss: "40311171" },
        { name: "Urina 24h (creatinina)", category: "Urinálise", tuss: "40311180" },
        { name: "Urina 24h (cálcio)", category: "Urinálise", tuss: "40311198" },
        { name: "Urina 24h (ácido úrico)", category: "Urinálise", tuss: "40311201" },
        // Microbiologia
        { name: "Urocultura com antibiograma", category: "Microbiologia", tuss: "40310060" },
        { name: "Cultura de secreção vaginal", category: "Microbiologia", tuss: "40310078" },
        { name: "Cultura de secreção uretral", category: "Microbiologia", tuss: "40310086" },
        { name: "Hemocultura", category: "Microbiologia", tuss: "40310094" },
        { name: "Coprocultura", category: "Microbiologia", tuss: "40310108" },
        // Inflamação e Autoimunidade
        { name: "PCR (Proteína C-reativa)", category: "Inflamação", tuss: "40308111" },
        { name: "PCR ultrassensível", category: "Inflamação", tuss: "40308120" },
        { name: "VHS (Velocidade de hemossedimentação)", category: "Inflamação", tuss: "40304396" },
        { name: "FAN (Fator antinuclear)", category: "Autoimunidade", tuss: "40308138" },
        { name: "Fator reumatoide", category: "Autoimunidade", tuss: "40308146" },
        { name: "Anti-CCP", category: "Autoimunidade", tuss: "40308154" },
        { name: "Complemento C3", category: "Autoimunidade", tuss: "40308162" },
        { name: "Complemento C4", category: "Autoimunidade", tuss: "40308170" },
        // Sorologias
        { name: "HIV 1 e 2 (anticorpos)", category: "Sorologia", tuss: "40307220" },
        { name: "HTLV I e II", category: "Sorologia", tuss: "40307239" },
        { name: "VDRL", category: "Sorologia", tuss: "40307573" },
        { name: "FTA-ABS", category: "Sorologia", tuss: "40307581" },
        { name: "Hepatite B - HBsAg", category: "Sorologia", tuss: "40307131" },
        { name: "Hepatite B - Anti-HBs", category: "Sorologia", tuss: "40307140" },
        { name: "Hepatite B - Anti-HBc total", category: "Sorologia", tuss: "40307158" },
        { name: "Hepatite C - Anti-HCV", category: "Sorologia", tuss: "40307166" },
        { name: "Toxoplasmose IgG e IgM", category: "Sorologia", tuss: "40307522" },
        { name: "Rubéola IgG e IgM", category: "Sorologia", tuss: "40307450" },
        { name: "Citomegalovírus IgG e IgM", category: "Sorologia", tuss: "40307352" },
        { name: "Dengue IgG e IgM", category: "Sorologia", tuss: "40307360" },
        { name: "Dengue NS1", category: "Sorologia", tuss: "40307379" },
        // Parasitológico
        { name: "Parasitológico de fezes (3 amostras)", category: "Parasitologia", tuss: "40311040" },
        { name: "Pesquisa de sangue oculto nas fezes", category: "Parasitologia", tuss: "40311058" },
        // Cardíacos
        { name: "Troponina I", category: "Cardíaco", tuss: "40302598" },
        { name: "CK-MB", category: "Cardíaco", tuss: "40301656" },
        { name: "BNP (Peptídeo natriurético)", category: "Cardíaco", tuss: "40302644" },
        { name: "NT-proBNP", category: "Cardíaco", tuss: "40302652" },
        { name: "Homocisteína", category: "Cardíaco", tuss: "40302181" },
    ],
    imagem: [
        // Radiologia
        { name: "Raio-X de tórax PA", category: "Radiologia", tuss: "40801012" },
        { name: "Raio-X de tórax PA e perfil", category: "Radiologia", tuss: "40801020" },
        { name: "Raio-X de coluna cervical", category: "Radiologia", tuss: "40801039" },
        { name: "Raio-X de coluna torácica", category: "Radiologia", tuss: "40801047" },
        { name: "Raio-X de coluna lombar", category: "Radiologia", tuss: "40801055" },
        { name: "Raio-X de coluna lombossacra", category: "Radiologia", tuss: "40801063" },
        { name: "Raio-X de bacia", category: "Radiologia", tuss: "40801071" },
        { name: "Raio-X de mão e punho", category: "Radiologia", tuss: "40801080" },
        { name: "Raio-X de joelho", category: "Radiologia", tuss: "40801098" },
        { name: "Raio-X de tornozelo e pé", category: "Radiologia", tuss: "40801101" },
        { name: "Raio-X de ombro", category: "Radiologia", tuss: "40801110" },
        { name: "Raio-X de seios da face", category: "Radiologia", tuss: "40801128" },
        { name: "Raio-X de abdome simples", category: "Radiologia", tuss: "40801136" },
        // Ultrassonografia
        { name: "Ultrassonografia abdominal total", category: "Ultrassonografia", tuss: "40901017" },
        { name: "Ultrassonografia abdominal superior", category: "Ultrassonografia", tuss: "40901025" },
        { name: "Ultrassonografia de tireoide", category: "Ultrassonografia", tuss: "40901033" },
        { name: "Ultrassonografia de mamas", category: "Ultrassonografia", tuss: "40901041" },
        { name: "Ultrassonografia pélvica transvaginal", category: "Ultrassonografia", tuss: "40901050" },
        { name: "Ultrassonografia pélvica suprapúbica", category: "Ultrassonografia", tuss: "40901068" },
        { name: "Ultrassonografia de próstata via abdominal", category: "Ultrassonografia", tuss: "40901076" },
        { name: "Ultrassonografia de próstata transretal", category: "Ultrassonografia", tuss: "40901084" },
        { name: "Ultrassonografia de rins e vias urinárias", category: "Ultrassonografia", tuss: "40901092" },
        { name: "Ultrassonografia de bolsa escrotal", category: "Ultrassonografia", tuss: "40901106" },
        { name: "Ultrassonografia obstétrica", category: "Ultrassonografia", tuss: "40901114" },
        { name: "Ultrassonografia obstétrica morfológica", category: "Ultrassonografia", tuss: "40901122" },
        { name: "Ultrassonografia obstétrica com Doppler", category: "Ultrassonografia", tuss: "40901130" },
        { name: "Ultrassonografia de partes moles", category: "Ultrassonografia", tuss: "40901149" },
        { name: "Ultrassonografia de articulação", category: "Ultrassonografia", tuss: "40901157" },
        { name: "Doppler de carótidas e vertebrais", category: "Ultrassonografia", tuss: "40901165" },
        { name: "Doppler de membros inferiores arterial", category: "Ultrassonografia", tuss: "40901173" },
        { name: "Doppler de membros inferiores venoso", category: "Ultrassonografia", tuss: "40901181" },
        { name: "Doppler de membros superiores", category: "Ultrassonografia", tuss: "40901190" },
        // Cardiologia
        { name: "Eletrocardiograma (ECG)", category: "Cardiologia", tuss: "40101010" },
        { name: "Ecocardiograma transtorácico", category: "Cardiologia", tuss: "40101029" },
        { name: "Ecocardiograma com Doppler", category: "Cardiologia", tuss: "40101037" },
        { name: "Ecocardiograma de estresse", category: "Cardiologia", tuss: "40101045" },
        { name: "Holter 24h", category: "Cardiologia", tuss: "40101053" },
        { name: "MAPA 24h", category: "Cardiologia", tuss: "40101061" },
        { name: "Teste ergométrico", category: "Cardiologia", tuss: "40101070" },
        { name: "Cintilografia miocárdica", category: "Cardiologia", tuss: "40701018" },
        // Tomografia
        { name: "Tomografia de crânio", category: "Tomografia", tuss: "41001010" },
        { name: "Tomografia de tórax", category: "Tomografia", tuss: "41001029" },
        { name: "Tomografia de tórax alta resolução", category: "Tomografia", tuss: "41001037" },
        { name: "Tomografia de abdome total", category: "Tomografia", tuss: "41001045" },
        { name: "Tomografia de abdome e pelve", category: "Tomografia", tuss: "41001053" },
        { name: "Tomografia de coluna lombar", category: "Tomografia", tuss: "41001061" },
        { name: "Tomografia de coluna cervical", category: "Tomografia", tuss: "41001070" },
        { name: "Tomografia de seios da face", category: "Tomografia", tuss: "41001088" },
        { name: "Angiotomografia de aorta", category: "Tomografia", tuss: "41001096" },
        { name: "Angiotomografia coronariana", category: "Tomografia", tuss: "41001100" },
        // Ressonância
        { name: "Ressonância magnética de crânio", category: "Ressonância", tuss: "41101014" },
        { name: "Ressonância magnética de coluna cervical", category: "Ressonância", tuss: "41101022" },
        { name: "Ressonância magnética de coluna torácica", category: "Ressonância", tuss: "41101030" },
        { name: "Ressonância magnética de coluna lombar", category: "Ressonância", tuss: "41101049" },
        { name: "Ressonância magnética de joelho", category: "Ressonância", tuss: "41101057" },
        { name: "Ressonância magnética de ombro", category: "Ressonância", tuss: "41101065" },
        { name: "Ressonância magnética de punho", category: "Ressonância", tuss: "41101073" },
        { name: "Ressonância magnética de quadril", category: "Ressonância", tuss: "41101081" },
        { name: "Ressonância magnética de pelve", category: "Ressonância", tuss: "41101090" },
        { name: "Ressonância magnética de abdome", category: "Ressonância", tuss: "41101103" },
        { name: "Ressonância magnética de mama", category: "Ressonância", tuss: "41101111" },
        { name: "Ressonância magnética cardíaca", category: "Ressonância", tuss: "41101120" },
        // Mamografia e Densitometria
        { name: "Mamografia bilateral", category: "Mamografia", tuss: "40501012" },
        { name: "Mamografia digital bilateral", category: "Mamografia", tuss: "40501020" },
        { name: "Densitometria óssea (coluna e fêmur)", category: "Densidade Óssea", tuss: "40601013" },
        { name: "Densitometria óssea de corpo inteiro", category: "Densidade Óssea", tuss: "40601021" },
        // Endoscopia
        { name: "Endoscopia digestiva alta", category: "Endoscopia", tuss: "40201015" },
        { name: "Colonoscopia", category: "Endoscopia", tuss: "40201023" },
        { name: "Retossigmoidoscopia", category: "Endoscopia", tuss: "40201031" },
        // Outros
        { name: "Espirometria", category: "Pneumologia", tuss: "40401014" },
        { name: "Polissonografia", category: "Neurologia", tuss: "40201040" },
        { name: "Eletroencefalograma", category: "Neurologia", tuss: "40201058" },
        { name: "Eletroneuromiografia", category: "Neurologia", tuss: "40201066" },
        { name: "Audiometria", category: "Otorrino", tuss: "40201074" },
        { name: "Impedanciometria", category: "Otorrino", tuss: "40201082" },
        { name: "Fundoscopia", category: "Oftalmologia", tuss: "40201090" },
        { name: "Tonometria", category: "Oftalmologia", tuss: "40201104" },
    ],
};

// Protocolos clínicos - Conjuntos de exames por indicação
export const EXAM_PROTOCOLS = [
    {
        id: "gestacao-1tri",
        name: "Gestação - 1º Trimestre",
        icon: Baby,
        color: "pink",
        description: "Exames de rotina pré-natal inicial",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const, tuss: "40304361" },
            { name: "Tipagem sanguínea ABO-Rh", type: "laboratorial" as const, tuss: "40306070" },
            { name: "Coombs indireto", type: "laboratorial" as const, tuss: "40306054" },
            { name: "Glicemia de jejum", type: "laboratorial" as const, tuss: "40302040" },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const, tuss: "40311163" },
            { name: "Urocultura com antibiograma", type: "laboratorial" as const, tuss: "40310060" },
            { name: "VDRL", type: "laboratorial" as const, tuss: "40307573" },
            { name: "HIV 1 e 2 (anticorpos)", type: "laboratorial" as const, tuss: "40307220" },
            { name: "HTLV I e II", type: "laboratorial" as const, tuss: "40307239" },
            { name: "Hepatite B - HBsAg", type: "laboratorial" as const, tuss: "40307131" },
            { name: "Hepatite C - Anti-HCV", type: "laboratorial" as const, tuss: "40307166" },
            { name: "Toxoplasmose IgG e IgM", type: "laboratorial" as const, tuss: "40307522" },
            { name: "Rubéola IgG e IgM", type: "laboratorial" as const, tuss: "40307450" },
            { name: "Citomegalovírus IgG e IgM", type: "laboratorial" as const, tuss: "40307352" },
            { name: "TSH", type: "laboratorial" as const, tuss: "40316130" },
            { name: "T4 livre", type: "laboratorial" as const, tuss: "40316149" },
            { name: "Ultrassonografia obstétrica", type: "imagem" as const, tuss: "40901114" },
        ]
    },
    {
        id: "gestacao-2tri",
        name: "Gestação - 2º Trimestre",
        icon: Baby,
        color: "pink",
        description: "Exames de acompanhamento pré-natal",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const, tuss: "40304361" },
            { name: "Glicemia de jejum", type: "laboratorial" as const, tuss: "40302040" },
            { name: "Curva glicêmica (TTOG 75g)", type: "laboratorial" as const, tuss: "40302075" },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const, tuss: "40311163" },
            { name: "Urocultura com antibiograma", type: "laboratorial" as const, tuss: "40310060" },
            { name: "Toxoplasmose IgG e IgM", type: "laboratorial" as const, tuss: "40307522" },
            { name: "Hepatite B - HBsAg", type: "laboratorial" as const, tuss: "40307131" },
            { name: "HIV 1 e 2 (anticorpos)", type: "laboratorial" as const, tuss: "40307220" },
            { name: "VDRL", type: "laboratorial" as const, tuss: "40307573" },
            { name: "Ultrassonografia obstétrica morfológica", type: "imagem" as const, tuss: "40901122" },
        ]
    },
    {
        id: "gestacao-3tri",
        name: "Gestação - 3º Trimestre",
        icon: Baby,
        color: "pink",
        description: "Exames finais do pré-natal",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const, tuss: "40304361" },
            { name: "Glicemia de jejum", type: "laboratorial" as const, tuss: "40302040" },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const, tuss: "40311163" },
            { name: "Urocultura com antibiograma", type: "laboratorial" as const, tuss: "40310060" },
            { name: "VDRL", type: "laboratorial" as const, tuss: "40307573" },
            { name: "HIV 1 e 2 (anticorpos)", type: "laboratorial" as const, tuss: "40307220" },
            { name: "Hepatite B - HBsAg", type: "laboratorial" as const, tuss: "40307131" },
            { name: "Cultura de secreção vaginal", type: "laboratorial" as const, tuss: "40310078" },
            { name: "Ultrassonografia obstétrica com Doppler", type: "imagem" as const, tuss: "40901130" },
        ]
    },
    {
        id: "hipertensao",
        name: "Hipertensão",
        icon: HeartPulse,
        color: "red",
        description: "Avaliação inicial e follow-up HAS",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const, tuss: "40304361" },
            { name: "Glicemia de jejum", type: "laboratorial" as const, tuss: "40302040" },
            { name: "Hemoglobina glicada (HbA1c)", type: "laboratorial" as const, tuss: "40302067" },
            { name: "Colesterol total", type: "laboratorial" as const, tuss: "40301605" },
            { name: "HDL-colesterol", type: "laboratorial" as const, tuss: "40301583" },
            { name: "LDL-colesterol", type: "laboratorial" as const, tuss: "40301591" },
            { name: "Triglicerídeos", type: "laboratorial" as const, tuss: "40302571" },
            { name: "Creatinina", type: "laboratorial" as const, tuss: "40301630" },
            { name: "Ureia", type: "laboratorial" as const, tuss: "40302580" },
            { name: "Ácido úrico", type: "laboratorial" as const, tuss: "40301036" },
            { name: "Potássio", type: "laboratorial" as const, tuss: "40302415" },
            { name: "Sódio", type: "laboratorial" as const, tuss: "40302512" },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const, tuss: "40311163" },
            { name: "Microalbuminúria", type: "laboratorial" as const, tuss: "40302369" },
            { name: "Eletrocardiograma (ECG)", type: "imagem" as const, tuss: "40101010" },
        ]
    },
    {
        id: "checkup-homem",
        name: "Check-up Homem (40+)",
        icon: Stethoscope,
        color: "indigo",
        description: "Avaliação de saúde preventiva",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const, tuss: "40304361" },
            { name: "Glicemia de jejum", type: "laboratorial" as const, tuss: "40302040" },
            { name: "Hemoglobina glicada (HbA1c)", type: "laboratorial" as const, tuss: "40302067" },
            { name: "Colesterol total", type: "laboratorial" as const, tuss: "40301605" },
            { name: "HDL-colesterol", type: "laboratorial" as const, tuss: "40301583" },
            { name: "LDL-colesterol", type: "laboratorial" as const, tuss: "40301591" },
            { name: "Triglicerídeos", type: "laboratorial" as const, tuss: "40302571" },
            { name: "Creatinina", type: "laboratorial" as const, tuss: "40301630" },
            { name: "Ureia", type: "laboratorial" as const, tuss: "40302580" },
            { name: "Ácido úrico", type: "laboratorial" as const, tuss: "40301036" },
            { name: "TGO (AST)", type: "laboratorial" as const, tuss: "40302555" },
            { name: "TGP (ALT)", type: "laboratorial" as const, tuss: "40302563" },
            { name: "Gama GT", type: "laboratorial" as const, tuss: "40301800" },
            { name: "TSH", type: "laboratorial" as const, tuss: "40316130" },
            { name: "PSA total", type: "laboratorial" as const, tuss: "40316505" },
            { name: "PSA livre", type: "laboratorial" as const, tuss: "40316513" },
            { name: "Vitamina D (25-OH)", type: "laboratorial" as const, tuss: "40302610" },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const, tuss: "40311163" },
            { name: "Pesquisa de sangue oculto nas fezes", type: "laboratorial" as const, tuss: "40311058" },
            { name: "Eletrocardiograma (ECG)", type: "imagem" as const, tuss: "40101010" },
            { name: "Ultrassonografia abdominal total", type: "imagem" as const, tuss: "40901017" },
        ]
    },
    {
        id: "checkup-mulher",
        name: "Check-up Mulher (40+)",
        icon: Stethoscope,
        color: "blue",
        description: "Avaliação de saúde preventiva",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const, tuss: "40304361" },
            { name: "Glicemia de jejum", type: "laboratorial" as const, tuss: "40302040" },
            { name: "Hemoglobina glicada (HbA1c)", type: "laboratorial" as const, tuss: "40302067" },
            { name: "Colesterol total", type: "laboratorial" as const, tuss: "40301605" },
            { name: "HDL-colesterol", type: "laboratorial" as const, tuss: "40301583" },
            { name: "LDL-colesterol", type: "laboratorial" as const, tuss: "40301591" },
            { name: "Triglicerídeos", type: "laboratorial" as const, tuss: "40302571" },
            { name: "Creatinina", type: "laboratorial" as const, tuss: "40301630" },
            { name: "Ureia", type: "laboratorial" as const, tuss: "40302580" },
            { name: "TGO (AST)", type: "laboratorial" as const, tuss: "40302555" },
            { name: "TGP (ALT)", type: "laboratorial" as const, tuss: "40302563" },
            { name: "TSH", type: "laboratorial" as const, tuss: "40316130" },
            { name: "T4 livre", type: "laboratorial" as const, tuss: "40316149" },
            { name: "Vitamina D (25-OH)", type: "laboratorial" as const, tuss: "40302610" },
            { name: "Cálcio total", type: "laboratorial" as const, tuss: "40301494" },
            { name: "Ferritina", type: "laboratorial" as const, tuss: "40301745" },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const, tuss: "40311163" },
            { name: "Pesquisa de sangue oculto nas fezes", type: "laboratorial" as const, tuss: "40311058" },
            { name: "Eletrocardiograma (ECG)", type: "imagem" as const, tuss: "40101010" },
            { name: "Mamografia bilateral", type: "imagem" as const, tuss: "40501012" },
            { name: "Ultrassonografia de mamas", type: "imagem" as const, tuss: "40901041" },
            { name: "Ultrassonografia pélvica transvaginal", type: "imagem" as const, tuss: "40901050" },
            { name: "Densitometria óssea (coluna e fêmur)", type: "imagem" as const, tuss: "40601013" },
        ]
    },
    {
        id: "anemia",
        name: "Anemia",
        icon: FlaskConical,
        color: "orange",
        description: "Diagnóstico diferencial de anemias",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const, tuss: "40304361" },
            { name: "Reticulócitos", type: "laboratorial" as const, tuss: "40304370" },
            { name: "Ferritina", type: "laboratorial" as const, tuss: "40301745" },
            { name: "Ferro sérico", type: "laboratorial" as const, tuss: "40301737" },
            { name: "Capacidade total de ligação do ferro (TIBC)", type: "laboratorial" as const, tuss: "40301508" },
            { name: "Índice de saturação de transferrina", type: "laboratorial" as const, tuss: "40302547" },
            { name: "Vitamina B12", type: "laboratorial" as const, tuss: "40302601" },
            { name: "Ácido fólico", type: "laboratorial" as const, tuss: "40301044" },
            { name: "LDH (Desidrogenase láctica)", type: "laboratorial" as const, tuss: "40302300" },
            { name: "Bilirrubinas totais e frações", type: "laboratorial" as const, tuss: "40301346" },
            { name: "Coombs direto", type: "laboratorial" as const, tuss: "40306062" },
        ]
    },
    {
        id: "gastrointestinal",
        name: "Gastrointestinal",
        icon: Activity,
        color: "amber",
        description: "Avaliação hepática e pancreática",
        exams: [
            { name: "TGO (AST)", type: "laboratorial" as const, tuss: "40302555" },
            { name: "TGP (ALT)", type: "laboratorial" as const, tuss: "40302563" },
            { name: "Bilirrubinas totais e frações", type: "laboratorial" as const, tuss: "40301346" },
            { name: "Fosfatase alcalina", type: "laboratorial" as const, tuss: "40301753" },
            { name: "Gama GT", type: "laboratorial" as const, tuss: "40301800" },
            { name: "Amilase", type: "laboratorial" as const, tuss: "40301184" },
            { name: "Lipase", type: "laboratorial" as const, tuss: "40302326" },
            { name: "Albumina", type: "laboratorial" as const, tuss: "40301079" },
            { name: "Proteínas totais e frações", type: "laboratorial" as const, tuss: "40302423" },
        ]
    },
    {
        id: "ists",
        name: "Investigação de ISTs",
        icon: Activity,
        color: "purple",
        description: "Rastreio de infecções sexualmente transmissíveis",
        exams: [
            { name: "HIV 1 e 2 (anticorpos)", type: "laboratorial" as const, tuss: "40307220" },
            { name: "VDRL", type: "laboratorial" as const, tuss: "40307573" },
            { name: "FTA-ABS", type: "laboratorial" as const, tuss: "40307581" },
            { name: "Hepatite B - HBsAg", type: "laboratorial" as const, tuss: "40307131" },
            { name: "Hepatite B - Anti-HBs", type: "laboratorial" as const, tuss: "40307140" },
            { name: "Hepatite B - Anti-HBc total", type: "laboratorial" as const, tuss: "40307158" },
            { name: "Hepatite C - Anti-HCV", type: "laboratorial" as const, tuss: "40307166" },
            { name: "HTLV I e II", type: "laboratorial" as const, tuss: "40307239" },
            { name: "Cultura de secreção uretral", type: "laboratorial" as const, tuss: "40310086" },
            { name: "Cultura de secreção vaginal", type: "laboratorial" as const, tuss: "40310078" },
        ]
    },
];

// Todos os exames em uma lista única para busca
export const ALL_EXAMS = [
    ...EXAM_DATABASE.laboratorial.map(e => ({ ...e, type: 'laboratorial' as const })),
    ...EXAM_DATABASE.imagem.map(e => ({ ...e, type: 'imagem' as const })),
];

// Cores dos protocolos para uso compartilhado
export const PROTOCOLS_COLORS: Record<string, { bg: string, border: string, iconBg: string, iconColor: string }> = {
    pink: { bg: "#fdf2f8", border: "#fce7f3", iconBg: "#fce7f3", iconColor: "#db2777" },
    red: { bg: "#fef2f2", border: "#fee2e2", iconBg: "#fee2e2", iconColor: "#dc2626" },
    orange: { bg: "#fff7ed", border: "#ffedd5", iconBg: "#ffedd5", iconColor: "#ea580c" },
    amber: { bg: "#fffbeb", border: "#fef3c7", iconBg: "#fef3c7", iconColor: "#d97706" },
    yellow: { bg: "#fefce8", border: "#fef9c3", iconBg: "#fef9c3", iconColor: "#ca8a04" },
    green: { bg: "#f0fdf4", border: "#dcfce7", iconBg: "#dcfce7", iconColor: "#16a34a" },
    emerald: { bg: "#ecfdf5", border: "#d1fae5", iconBg: "#d1fae5", iconColor: "#059669" },
    teal: { bg: "#f0fdfa", border: "#ccfbf1", iconBg: "#ccfbf1", iconColor: "#0d9488" },
    cyan: { bg: "#ecfeff", border: "#cffafe", iconBg: "#cffafe", iconColor: "#0891b2" },
    sky: { bg: "#f0f9ff", border: "#e0f2fe", iconBg: "#e0f2fe", iconColor: "#0284c7" },
    blue: { bg: "#eff6ff", border: "#dbeafe", iconBg: "#dbeafe", iconColor: "#2563eb" },
    indigo: { bg: "#eef2ff", border: "#e0e7ff", iconBg: "#e0e7ff", iconColor: "#4f46e5" },
    violet: { bg: "#f5f3ff", border: "#ede9fe", iconBg: "#ede9fe", iconColor: "#7c3aed" },
    purple: { bg: "#faf5ff", border: "#f3e8ff", iconBg: "#f3e8ff", iconColor: "#9333ea" },
    fuchsia: { bg: "#fdf4ff", border: "#fae8ff", iconBg: "#fae8ff", iconColor: "#c026d3" },
    rose: { bg: "#fff1f2", border: "#ffe4e6", iconBg: "#ffe4e6", iconColor: "#e11d48" },
    gray: { bg: "#f9fafb", border: "#e5e7eb", iconBg: "#f3f4f6", iconColor: "#4b5563" },
};
