import {
    Baby,
    HeartPulse,
    FlaskConical,
    Activity,
    Stethoscope
} from "lucide-react";

// Banco de dados de exames comuns - EXPANDIDO
export const EXAM_DATABASE = {
    laboratorial: [
        // Hematologia
        { name: "Hemograma completo", category: "Hematologia" },
        { name: "Reticulócitos", category: "Hematologia" },
        { name: "Contagem de plaquetas", category: "Hematologia" },
        { name: "Tipagem sanguínea ABO-Rh", category: "Hematologia" },
        { name: "Coombs direto", category: "Hematologia" },
        { name: "Coombs indireto", category: "Hematologia" },
        // Bioquímica - Glicemia
        { name: "Glicemia de jejum", category: "Glicemia" },
        { name: "Glicemia pós-prandial", category: "Glicemia" },
        { name: "Hemoglobina glicada (HbA1c)", category: "Glicemia" },
        { name: "Curva glicêmica (TTOG 75g)", category: "Glicemia" },
        { name: "Frutosamina", category: "Glicemia" },
        // Lipidograma
        { name: "Colesterol total", category: "Lipidograma" },
        { name: "HDL-colesterol", category: "Lipidograma" },
        { name: "LDL-colesterol", category: "Lipidograma" },
        { name: "VLDL-colesterol", category: "Lipidograma" },
        { name: "Triglicerídeos", category: "Lipidograma" },
        { name: "Apolipoproteína A1", category: "Lipidograma" },
        { name: "Apolipoproteína B", category: "Lipidograma" },
        { name: "Lipoproteína (a)", category: "Lipidograma" },
        // Função Renal
        { name: "Ureia", category: "Função Renal" },
        { name: "Creatinina", category: "Função Renal" },
        { name: "Ácido úrico", category: "Função Renal" },
        { name: "Clearance de creatinina", category: "Função Renal" },
        { name: "Cistatina C", category: "Função Renal" },
        { name: "Microalbuminúria", category: "Função Renal" },
        { name: "Relação albumina/creatinina urinária", category: "Função Renal" },
        // Função Hepática
        { name: "TGO (AST)", category: "Função Hepática" },
        { name: "TGP (ALT)", category: "Função Hepática" },
        { name: "Gama GT", category: "Função Hepática" },
        { name: "Fosfatase alcalina", category: "Função Hepática" },
        { name: "Bilirrubinas totais e frações", category: "Função Hepática" },
        { name: "Albumina", category: "Função Hepática" },
        { name: "Proteínas totais e frações", category: "Função Hepática" },
        { name: "LDH (Desidrogenase láctica)", category: "Função Hepática" },
        { name: "Amilase", category: "Função Hepática" },
        { name: "Lipase", category: "Função Hepática" },
        // Tireoide
        { name: "TSH", category: "Tireoide" },
        { name: "T4 livre", category: "Tireoide" },
        { name: "T4 total", category: "Tireoide" },
        { name: "T3 livre", category: "Tireoide" },
        { name: "T3 total", category: "Tireoide" },
        { name: "Anti-TPO", category: "Tireoide" },
        { name: "Anti-tireoglobulina", category: "Tireoide" },
        { name: "Tireoglobulina", category: "Tireoide" },
        // Vitaminas e Minerais
        { name: "Vitamina D (25-OH)", category: "Vitaminas" },
        { name: "Vitamina B12", category: "Vitaminas" },
        { name: "Ácido fólico", category: "Vitaminas" },
        { name: "Vitamina B1 (Tiamina)", category: "Vitaminas" },
        { name: "Vitamina B6", category: "Vitaminas" },
        { name: "Zinco", category: "Vitaminas" },
        { name: "Selênio", category: "Vitaminas" },
        // Metabolismo do Ferro
        { name: "Ferritina", category: "Ferro" },
        { name: "Ferro sérico", category: "Ferro" },
        { name: "Capacidade total de ligação do ferro (TIBC)", category: "Ferro" },
        { name: "Índice de saturação de transferrina", category: "Ferro" },
        { name: "Transferrina", category: "Ferro" },
        // Eletrólitos
        { name: "Sódio", category: "Eletrólitos" },
        { name: "Potássio", category: "Eletrólitos" },
        { name: "Cálcio total", category: "Eletrólitos" },
        { name: "Cálcio iônico", category: "Eletrólitos" },
        { name: "Magnésio", category: "Eletrólitos" },
        { name: "Fósforo", category: "Eletrólitos" },
        { name: "Cloro", category: "Eletrólitos" },
        // Coagulação
        { name: "Tempo de protrombina (TP)", category: "Coagulação" },
        { name: "INR", category: "Coagulação" },
        { name: "TTPa", category: "Coagulação" },
        { name: "Fibrinogênio", category: "Coagulação" },
        { name: "D-dímero", category: "Coagulação" },
        { name: "Tempo de sangramento", category: "Coagulação" },
        // Hormônios
        { name: "Beta-HCG quantitativo", category: "Hormônios" },
        { name: "Prolactina", category: "Hormônios" },
        { name: "Cortisol", category: "Hormônios" },
        { name: "Insulina basal", category: "Hormônios" },
        { name: "HOMA-IR", category: "Hormônios" },
        { name: "FSH", category: "Hormônios" },
        { name: "LH", category: "Hormônios" },
        { name: "Estradiol", category: "Hormônios" },
        { name: "Progesterona", category: "Hormônios" },
        { name: "Testosterona total", category: "Hormônios" },
        { name: "Testosterona livre", category: "Hormônios" },
        { name: "DHEA-S", category: "Hormônios" },
        { name: "PTH (Paratormônio)", category: "Hormônios" },
        { name: "GH (Hormônio do crescimento)", category: "Hormônios" },
        { name: "IGF-1", category: "Hormônios" },
        // Marcadores Tumorais
        { name: "PSA total", category: "Marcadores Tumorais" },
        { name: "PSA livre", category: "Marcadores Tumorais" },
        { name: "CEA", category: "Marcadores Tumorais" },
        { name: "CA 125", category: "Marcadores Tumorais" },
        { name: "CA 19-9", category: "Marcadores Tumorais" },
        { name: "CA 15-3", category: "Marcadores Tumorais" },
        { name: "AFP (Alfafetoproteína)", category: "Marcadores Tumorais" },
        // Urinálise
        { name: "EAS (Urina tipo I)", category: "Urinálise" },
        { name: "Urina 24h (proteínas)", category: "Urinálise" },
        { name: "Urina 24h (creatinina)", category: "Urinálise" },
        { name: "Urina 24h (cálcio)", category: "Urinálise" },
        { name: "Urina 24h (ácido úrico)", category: "Urinálise" },
        // Microbiologia
        { name: "Urocultura com antibiograma", category: "Microbiologia" },
        { name: "Cultura de secreção vaginal", category: "Microbiologia" },
        { name: "Cultura de secreção uretral", category: "Microbiologia" },
        { name: "Hemocultura", category: "Microbiologia" },
        { name: "Coprocultura", category: "Microbiologia" },
        // Inflamação e Autoimunidade
        { name: "PCR (Proteína C-reativa)", category: "Inflamação" },
        { name: "PCR ultrassensível", category: "Inflamação" },
        { name: "VHS (Velocidade de hemossedimentação)", category: "Inflamação" },
        { name: "FAN (Fator antinuclear)", category: "Autoimunidade" },
        { name: "Fator reumatoide", category: "Autoimunidade" },
        { name: "Anti-CCP", category: "Autoimunidade" },
        { name: "Complemento C3", category: "Autoimunidade" },
        { name: "Complemento C4", category: "Autoimunidade" },
        // Sorologias
        { name: "HIV 1 e 2 (anticorpos)", category: "Sorologia" },
        { name: "HTLV I e II", category: "Sorologia" },
        { name: "VDRL", category: "Sorologia" },
        { name: "FTA-ABS", category: "Sorologia" },
        { name: "Hepatite B - HBsAg", category: "Sorologia" },
        { name: "Hepatite B - Anti-HBs", category: "Sorologia" },
        { name: "Hepatite B - Anti-HBc total", category: "Sorologia" },
        { name: "Hepatite C - Anti-HCV", category: "Sorologia" },
        { name: "Toxoplasmose IgG e IgM", category: "Sorologia" },
        { name: "Rubéola IgG e IgM", category: "Sorologia" },
        { name: "Citomegalovírus IgG e IgM", category: "Sorologia" },
        { name: "Dengue IgG e IgM", category: "Sorologia" },
        { name: "Dengue NS1", category: "Sorologia" },
        // Parasitológico
        { name: "Parasitológico de fezes (3 amostras)", category: "Parasitologia" },
        { name: "Pesquisa de sangue oculto nas fezes", category: "Parasitologia" },
        // Cardíacos
        { name: "Troponina I", category: "Cardíaco" },
        { name: "CK-MB", category: "Cardíaco" },
        { name: "BNP (Peptídeo natriurético)", category: "Cardíaco" },
        { name: "NT-proBNP", category: "Cardíaco" },
        { name: "Homocisteína", category: "Cardíaco" },
    ],
    imagem: [
        // Radiologia
        { name: "Raio-X de tórax PA", category: "Radiologia" },
        { name: "Raio-X de tórax PA e perfil", category: "Radiologia" },
        { name: "Raio-X de coluna cervical", category: "Radiologia" },
        { name: "Raio-X de coluna torácica", category: "Radiologia" },
        { name: "Raio-X de coluna lombar", category: "Radiologia" },
        { name: "Raio-X de coluna lombossacra", category: "Radiologia" },
        { name: "Raio-X de bacia", category: "Radiologia" },
        { name: "Raio-X de mão e punho", category: "Radiologia" },
        { name: "Raio-X de joelho", category: "Radiologia" },
        { name: "Raio-X de tornozelo e pé", category: "Radiologia" },
        { name: "Raio-X de ombro", category: "Radiologia" },
        { name: "Raio-X de seios da face", category: "Radiologia" },
        { name: "Raio-X de abdome simples", category: "Radiologia" },
        // Ultrassonografia
        { name: "Ultrassonografia abdominal total", category: "Ultrassonografia" },
        { name: "Ultrassonografia abdominal superior", category: "Ultrassonografia" },
        { name: "Ultrassonografia de tireoide", category: "Ultrassonografia" },
        { name: "Ultrassonografia de mamas", category: "Ultrassonografia" },
        { name: "Ultrassonografia pélvica transvaginal", category: "Ultrassonografia" },
        { name: "Ultrassonografia pélvica suprapúbica", category: "Ultrassonografia" },
        { name: "Ultrassonografia de próstata via abdominal", category: "Ultrassonografia" },
        { name: "Ultrassonografia de próstata transretal", category: "Ultrassonografia" },
        { name: "Ultrassonografia de rins e vias urinárias", category: "Ultrassonografia" },
        { name: "Ultrassonografia de bolsa escrotal", category: "Ultrassonografia" },
        { name: "Ultrassonografia obstétrica", category: "Ultrassonografia" },
        { name: "Ultrassonografia obstétrica morfológica", category: "Ultrassonografia" },
        { name: "Ultrassonografia obstétrica com Doppler", category: "Ultrassonografia" },
        { name: "Ultrassonografia de partes moles", category: "Ultrassonografia" },
        { name: "Ultrassonografia de articulação", category: "Ultrassonografia" },
        { name: "Doppler de carótidas e vertebrais", category: "Ultrassonografia" },
        { name: "Doppler de membros inferiores arterial", category: "Ultrassonografia" },
        { name: "Doppler de membros inferiores venoso", category: "Ultrassonografia" },
        { name: "Doppler de membros superiores", category: "Ultrassonografia" },
        // Cardiologia
        { name: "Eletrocardiograma (ECG)", category: "Cardiologia" },
        { name: "Ecocardiograma transtorácico", category: "Cardiologia" },
        { name: "Ecocardiograma com Doppler", category: "Cardiologia" },
        { name: "Ecocardiograma de estresse", category: "Cardiologia" },
        { name: "Holter 24h", category: "Cardiologia" },
        { name: "MAPA 24h", category: "Cardiologia" },
        { name: "Teste ergométrico", category: "Cardiologia" },
        { name: "Cintilografia miocárdica", category: "Cardiologia" },
        // Tomografia
        { name: "Tomografia de crânio", category: "Tomografia" },
        { name: "Tomografia de tórax", category: "Tomografia" },
        { name: "Tomografia de tórax alta resolução", category: "Tomografia" },
        { name: "Tomografia de abdome total", category: "Tomografia" },
        { name: "Tomografia de abdome e pelve", category: "Tomografia" },
        { name: "Tomografia de coluna lombar", category: "Tomografia" },
        { name: "Tomografia de coluna cervical", category: "Tomografia" },
        { name: "Tomografia de seios da face", category: "Tomografia" },
        { name: "Angiotomografia de aorta", category: "Tomografia" },
        { name: "Angiotomografia coronariana", category: "Tomografia" },
        // Ressonância
        { name: "Ressonância magnética de crânio", category: "Ressonância" },
        { name: "Ressonância magnética de coluna cervical", category: "Ressonância" },
        { name: "Ressonância magnética de coluna torácica", category: "Ressonância" },
        { name: "Ressonância magnética de coluna lombar", category: "Ressonância" },
        { name: "Ressonância magnética de joelho", category: "Ressonância" },
        { name: "Ressonância magnética de ombro", category: "Ressonância" },
        { name: "Ressonância magnética de punho", category: "Ressonância" },
        { name: "Ressonância magnética de quadril", category: "Ressonância" },
        { name: "Ressonância magnética de pelve", category: "Ressonância" },
        { name: "Ressonância magnética de abdome", category: "Ressonância" },
        { name: "Ressonância magnética de mama", category: "Ressonância" },
        { name: "Ressonância magnética cardíaca", category: "Ressonância" },
        // Mamografia e Densitometria
        { name: "Mamografia bilateral", category: "Mamografia" },
        { name: "Mamografia digital bilateral", category: "Mamografia" },
        { name: "Densitometria óssea (coluna e fêmur)", category: "Densidade Óssea" },
        { name: "Densitometria óssea de corpo inteiro", category: "Densidade Óssea" },
        // Endoscopia
        { name: "Endoscopia digestiva alta", category: "Endoscopia" },
        { name: "Colonoscopia", category: "Endoscopia" },
        { name: "Retossigmoidoscopia", category: "Endoscopia" },
        // Outros
        { name: "Espirometria", category: "Pneumologia" },
        { name: "Polissonografia", category: "Neurologia" },
        { name: "Eletroencefalograma", category: "Neurologia" },
        { name: "Eletroneuromiografia", category: "Neurologia" },
        { name: "Audiometria", category: "Otorrino" },
        { name: "Impedanciometria", category: "Otorrino" },
        { name: "Fundoscopia", category: "Oftalmologia" },
        { name: "Tonometria", category: "Oftalmologia" },
    ],
};

// Protocolos clínicos - Conjuntos de exames por indicação
export const EXAM_PROTOCOLS = [
    {
        id: "gestacao-1tri",
        name: "Gestação - 1º Trimestre",
        icon: Baby,
        color: "pink",
        description: "Exames de rotina pré-natal inicial",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const },
            { name: "Tipagem sanguínea ABO-Rh", type: "laboratorial" as const },
            { name: "Coombs indireto", type: "laboratorial" as const },
            { name: "Glicemia de jejum", type: "laboratorial" as const },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const },
            { name: "Urocultura com antibiograma", type: "laboratorial" as const },
            { name: "VDRL", type: "laboratorial" as const },
            { name: "HIV 1 e 2 (anticorpos)", type: "laboratorial" as const },
            { name: "HTLV I e II", type: "laboratorial" as const },
            { name: "Hepatite B - HBsAg", type: "laboratorial" as const },
            { name: "Hepatite C - Anti-HCV", type: "laboratorial" as const },
            { name: "Toxoplasmose IgG e IgM", type: "laboratorial" as const },
            { name: "Rubéola IgG e IgM", type: "laboratorial" as const },
            { name: "Citomegalovírus IgG e IgM", type: "laboratorial" as const },
            { name: "TSH", type: "laboratorial" as const },
            { name: "T4 livre", type: "laboratorial" as const },
            { name: "Ultrassonografia obstétrica", type: "imagem" as const },
        ]
    },
    {
        id: "gestacao-2tri",
        name: "Gestação - 2º Trimestre",
        icon: Baby,
        color: "pink",
        description: "Exames de acompanhamento pré-natal",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const },
            { name: "Glicemia de jejum", type: "laboratorial" as const },
            { name: "Curva glicêmica (TTOG 75g)", type: "laboratorial" as const },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const },
            { name: "Urocultura com antibiograma", type: "laboratorial" as const },
            { name: "Toxoplasmose IgG e IgM", type: "laboratorial" as const },
            { name: "Hepatite B - HBsAg", type: "laboratorial" as const },
            { name: "HIV 1 e 2 (anticorpos)", type: "laboratorial" as const },
            { name: "VDRL", type: "laboratorial" as const },
            { name: "Ultrassonografia obstétrica morfológica", type: "imagem" as const },
        ]
    },
    {
        id: "gestacao-3tri",
        name: "Gestação - 3º Trimestre",
        icon: Baby,
        color: "pink",
        description: "Exames finais do pré-natal",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const },
            { name: "Glicemia de jejum", type: "laboratorial" as const },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const },
            { name: "Urocultura com antibiograma", type: "laboratorial" as const },
            { name: "VDRL", type: "laboratorial" as const },
            { name: "HIV 1 e 2 (anticorpos)", type: "laboratorial" as const },
            { name: "Hepatite B - HBsAg", type: "laboratorial" as const },
            { name: "Cultura de secreção vaginal", type: "laboratorial" as const },
            { name: "Ultrassonografia obstétrica com Doppler", type: "imagem" as const },
        ]
    },
    {
        id: "hipertensao",
        name: "Hipertensão",
        icon: HeartPulse,
        color: "red",
        description: "Avaliação inicial e follow-up HAS",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const },
            { name: "Glicemia de jejum", type: "laboratorial" as const },
            { name: "Hemoglobina glicada (HbA1c)", type: "laboratorial" as const },
            { name: "Colesterol total", type: "laboratorial" as const },
            { name: "HDL-colesterol", type: "laboratorial" as const },
            { name: "LDL-colesterol", type: "laboratorial" as const },
            { name: "Triglicerídeos", type: "laboratorial" as const },
            { name: "Creatinina", type: "laboratorial" as const },
            { name: "Ureia", type: "laboratorial" as const },
            { name: "Ácido úrico", type: "laboratorial" as const },
            { name: "Potássio", type: "laboratorial" as const },
            { name: "Sódio", type: "laboratorial" as const },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const },
            { name: "Microalbuminúria", type: "laboratorial" as const },
            { name: "Eletrocardiograma (ECG)", type: "imagem" as const },
        ]
    },
    {
        id: "checkup-homem",
        name: "Check-up Homem (40+)",
        icon: Stethoscope,
        color: "indigo",
        description: "Avaliação de saúde preventiva",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const },
            { name: "Glicemia de jejum", type: "laboratorial" as const },
            { name: "Hemoglobina glicada (HbA1c)", type: "laboratorial" as const },
            { name: "Colesterol total", type: "laboratorial" as const },
            { name: "HDL-colesterol", type: "laboratorial" as const },
            { name: "LDL-colesterol", type: "laboratorial" as const },
            { name: "Triglicerídeos", type: "laboratorial" as const },
            { name: "Creatinina", type: "laboratorial" as const },
            { name: "Ureia", type: "laboratorial" as const },
            { name: "Ácido úrico", type: "laboratorial" as const },
            { name: "TGO (AST)", type: "laboratorial" as const },
            { name: "TGP (ALT)", type: "laboratorial" as const },
            { name: "Gama GT", type: "laboratorial" as const },
            { name: "TSH", type: "laboratorial" as const },
            { name: "PSA total", type: "laboratorial" as const },
            { name: "PSA livre", type: "laboratorial" as const },
            { name: "Vitamina D (25-OH)", type: "laboratorial" as const },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const },
            { name: "Pesquisa de sangue oculto nas fezes", type: "laboratorial" as const },
            { name: "Eletrocardiograma (ECG)", type: "imagem" as const },
            { name: "Ultrassonografia abdominal total", type: "imagem" as const },
        ]
    },
    {
        id: "checkup-mulher",
        name: "Check-up Mulher (40+)",
        icon: Stethoscope,
        color: "blue",
        description: "Avaliação de saúde preventiva",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const },
            { name: "Glicemia de jejum", type: "laboratorial" as const },
            { name: "Hemoglobina glicada (HbA1c)", type: "laboratorial" as const },
            { name: "Colesterol total", type: "laboratorial" as const },
            { name: "HDL-colesterol", type: "laboratorial" as const },
            { name: "LDL-colesterol", type: "laboratorial" as const },
            { name: "Triglicerídeos", type: "laboratorial" as const },
            { name: "Creatinina", type: "laboratorial" as const },
            { name: "Ureia", type: "laboratorial" as const },
            { name: "TGO (AST)", type: "laboratorial" as const },
            { name: "TGP (ALT)", type: "laboratorial" as const },
            { name: "TSH", type: "laboratorial" as const },
            { name: "T4 livre", type: "laboratorial" as const },
            { name: "Vitamina D (25-OH)", type: "laboratorial" as const },
            { name: "Cálcio total", type: "laboratorial" as const },
            { name: "Ferritina", type: "laboratorial" as const },
            { name: "EAS (Urina tipo I)", type: "laboratorial" as const },
            { name: "Pesquisa de sangue oculto nas fezes", type: "laboratorial" as const },
            { name: "Eletrocardiograma (ECG)", type: "imagem" as const },
            { name: "Mamografia bilateral", type: "imagem" as const },
            { name: "Ultrassonografia de mamas", type: "imagem" as const },
            { name: "Ultrassonografia pélvica transvaginal", type: "imagem" as const },
            { name: "Densitometria óssea (coluna e fêmur)", type: "imagem" as const },
        ]
    },
    {
        id: "anemia",
        name: "Anemia",
        icon: FlaskConical,
        color: "orange",
        description: "Diagnóstico diferencial de anemias",
        exams: [
            { name: "Hemograma completo", type: "laboratorial" as const },
            { name: "Reticulócitos", type: "laboratorial" as const },
            { name: "Ferritina", type: "laboratorial" as const },
            { name: "Ferro sérico", type: "laboratorial" as const },
            { name: "Capacidade total de ligação do ferro (TIBC)", type: "laboratorial" as const },
            { name: "Índice de saturação de transferrina", type: "laboratorial" as const },
            { name: "Vitamina B12", type: "laboratorial" as const },
            { name: "Ácido fólico", type: "laboratorial" as const },
            { name: "LDH (Desidrogenase láctica)", type: "laboratorial" as const },
            { name: "Bilirrubinas totais e frações", type: "laboratorial" as const },
            { name: "Coombs direto", type: "laboratorial" as const },
        ]
    },
    {
        id: "gastrointestinal",
        name: "Gastrointestinal",
        icon: Activity,
        color: "amber",
        description: "Avaliação hepática e pancreática",
        exams: [
            { name: "TGO (AST)", type: "laboratorial" as const },
            { name: "TGP (ALT)", type: "laboratorial" as const },
            { name: "Bilirrubinas totais e frações", type: "laboratorial" as const },
            { name: "Fosfatase alcalina", type: "laboratorial" as const },
            { name: "Gama GT", type: "laboratorial" as const },
            { name: "Amilase", type: "laboratorial" as const },
            { name: "Lipase", type: "laboratorial" as const },
            { name: "Albumina", type: "laboratorial" as const },
            { name: "Proteínas totais e frações", type: "laboratorial" as const },
        ]
    },
    {
        id: "ists",
        name: "Investigação de ISTs",
        icon: Activity,
        color: "purple",
        description: "Rastreio de infecções sexualmente transmissíveis",
        exams: [
            { name: "HIV 1 e 2 (anticorpos)", type: "laboratorial" as const },
            { name: "VDRL", type: "laboratorial" as const },
            { name: "FTA-ABS", type: "laboratorial" as const },
            { name: "Hepatite B - HBsAg", type: "laboratorial" as const },
            { name: "Hepatite B - Anti-HBs", type: "laboratorial" as const },
            { name: "Hepatite B - Anti-HBc total", type: "laboratorial" as const },
            { name: "Hepatite C - Anti-HCV", type: "laboratorial" as const },
            { name: "HTLV I e II", type: "laboratorial" as const },
            { name: "Cultura de secreção uretral", type: "laboratorial" as const },
            { name: "Cultura de secreção vaginal", type: "laboratorial" as const },
        ]
    },
];

// Todos os exames em uma lista única para busca
export const ALL_EXAMS = [
    ...EXAM_DATABASE.laboratorial.map(e => ({ ...e, type: 'laboratorial' as const })),
    ...EXAM_DATABASE.imagem.map(e => ({ ...e, type: 'imagem' as const })),
];
